[package]
name = "bondebarras-core"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
octocrab.workspace = true
http.workspace = true
ratatui.workspace = true
crossterm.workspace = true
chrono.workspace = true
futures.workspace = true

[dev-dependencies]
wiremock.workspace = true

[lints]
workspace = true
